baseurl = "/"
languageCode = "en"
defaultContentLanguage = "en"
title = "Tour with Mark"
theme = "hugo-theme-dream"

# copyright = ""

googleAnalytics = "UA-177079344-1"

disqusShortname = "https-tourwithmark-com.disqus.com"

# enableRobotsTXT = true

[params]
  background = "black"
  # backgroundImage = "/me/background.jpg"
  linkColor = "seagreen"

  author = "Mark Gingrass"
  # description = ""
  avatar = "/img/avatar.jpg"
  motto = "Tour with Mark"

  # rss = true

  # utterancesRepo = ""
  
  email = "mark.gingrass@gmail.com"
  twitter = "MarkGingrass"
  # facebook = ""
  # instagram = ""
  linkedin = "markgingrass/"
  github = "mtgingrass"
  # stackoverflow = ""
  # codepen = ""

  siteStartYear = 2020

  # favicon = "/favicon.ico"

  # options
  showSummaryCoverInPost = true

  # dark mode
  darkLinkColor = "darkseagreen"
  darkNav = true 
  dark404 = true
  
  highlightjsVersion = "9.12.0"
  highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
  highlightjsLang = ["r", "yaml"]
  highlightjsTheme = "github"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
    unsafe = true