---
title: Upper Gauley Class V Rapids
output:
  html_document:
    toc: true
    theme: united
cover: /images/The Gauley Upper.jpg
author: mtgingrass
date: '2022-09-16'
slug: []
categories: [adventure]
tags: [rafting, whitewater, gauley, upper river, lower river, gorge]
summary: The Upper Gauley is the pinnacle of whitewater experiences and for experienced rafters only. This 11-mile section of the river requires all the paddling power you can muster and may be the most extreme trip most rafters will ever attempt. This is serious whitewater, and it’s an adventure you won’t forget!
---


# Adventures on the Gorge

I spent the weekend at Adventures on the Gorge with my girlfriend, Liz. We are both pretty adventurous and wanted this type of thrill. The check-in process was easy, and the front desk folks were very nice. We camped on the resort property the first night in one of the many camping areas. The facilities were pristine and well maintained. Our guide, KP, was extremely knowledgeable and fun to chat with on this trip. Overall, the river and rapids exceeded our expectations, and we would 100% make this trip again. We are already planning for more!


## Deluxe Gauley River Overnight

Let me start by stating that the Gauley River [Deluxe overnight trip](https://adventuresonthegorge.com/whitewater-rafting/deluxe-gauley-river-rafting-overnight/) was fantastic!


# Sliders at Rendezvous Lodge Bar

We showed up hungry at the [Rendezvous Lodge Bar](https://adventuresonthegorge.com/venue/rendezvous-river-lodge/). So, we went to the bartender to order food, and the only thing on the menu were sliders. The sliders were pretty big, and it was plenty for two people. Not bad for $3 bucks! Not to mention that they were delicious. Excellent beer selection, and the prices were not bad at all.

At the bar, there was also live music playing (@GrizzleyGoat), a good amount of people, and everyone seemed friendly. They have a cornhole area, a fire pit, and a volleyball court. Everything you would expect outdoors to be.

Other dining options:



* [Smokey’s on the Gorge](https://adventuresonthegorge.com/venue/smokeys-on-the-gorge/) - AOTG’s signature restaurant offering casual dining with a great view.
* [Canyon Falls Snack Shack](https://adventuresonthegorge.com/venue/canyon-falls-snack-shack/) - Located at the pool; however, we did not try this place out. 
* [Sweet Java Falls](https://adventuresonthegorge.com/venue/sweet-java-falls/) - Espresso, coffee, bagels, this place has you covered.
* [Chetty’s Pub](https://adventuresonthegorge.com/venue/chettys-pub/) - large deck overlooking the gorge and the after raft watch party location


# Chetty’s Pub


# The morning of the trip


# Upper Gauley

NOTES: A little practice run before the rapid. All the rocks have names. If a rapid si named after you - you did nothing good - [@KPRaftGuide](https://www.instagram.com/kpraftguide/?igshid=YmMyMTA2M2Y%3D)

Lost Paddle - Named after the first female raft guide down the Gauley. She lost her paddle. It was hung above the rapid until someone stole it. 


# Camping and Food

NOTES: gravel tent area, covered picnic tables, big fire pit. Hot showers. Great food. Lots of beer. 


# Lower Gauley


# Ray Ray

Jokes - not for kids. Hilarious! 

<iframe src="https://kit.co/embed?url=https%3A%2F%2Fkit.co%2FTechTeachCreate%2Fmy-streaming-kit" style="display: block; border: 0px; margin: 0 auto; width: 100%; height: 100vw; max-width: 700px; max-height: 700px" scrolling="no"></iframe>
