---
title: Hurricane Ian - Charleston, SC September 30, 2022
author: mtgingrass
date: '2022-09-30'
cover: /post/2022-09-30-hurricane-ian-charleston-sc-september-30-2022/images/Copy of Yellow Freelancer YouTube Thumbnail.jpg
slug: []
categories:
  - adventure
  - Charleston
tags:
  - hurricane
  - storm
  - rain
summary: Charleston’s historic downtown getting hit hard from Hurricane Ian. Newest footage. Florida officials said that at least 21 deaths were possibly linked to the storm that hit there two days ago — a toll they expected to rise in the coming days.
---

# GoPro Footage of Hurricane Ian Charleston, SC

Charleston’s historic downtown getting hit hard from Hurricane Ian. Newest footage. Florida officials said that at least 21 deaths were possibly linked to the storm that hit there two days ago — a toll they expected to rise in the coming days.

Full video, including first person [GoPro Hero 10 (Amazon Affilate Link)](https://amzn.to/3frhrdn) footage, is down below. 

<style>.embed-container { position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; } .embed-container iframe, .embed-container object, .embed-container embed { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }</style><div class='embed-container'><iframe src='https://www.youtube.com/embed/kxFbX9p8WNM' frameborder='0' allowfullscreen></iframe></div>


As an Amazon Associate, I earn from qualifying purchases. I used this battery pack and GoPro Hero 10 to film this adventure.

<iframe sandbox="allow-popups allow-scripts allow-modals allow-forms allow-same-origin" style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=kit-my_streaming-20&language=en_US&marketplace=amazon&region=US&placement=B0B96H7LGX&asins=B0B96H7LGX&linkId=d22fff55c8041cc39054aa8bb7651452&show_border=true&link_opens_in_new_window=true"></iframe>

<iframe sandbox="allow-popups allow-scripts allow-modals allow-forms allow-same-origin" style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=kit-my_streaming-20&language=en_US&marketplace=amazon&region=US&placement=B08KWDBHTN&asins=B08KWDBHTN&linkId=0346d2fa80121aaa457e49ddf398f5ad&show_border=true&link_opens_in_new_window=true"></iframe>
